import { afterEach, describe, expect, it } from 'vitest'
import { DistingDisplayApi } from '../../emulation/display-api'
import { loadLuaProgramRuntime } from '../../emulation/lua-runtime'
import { createDistingLuaTestEngine } from '../../testing/lua-test-environment'
import {
  createDefaultDisplayPrimitive,
  createEmptyDisplayDesign,
  createSequentialDisplayDesignIdFactory,
  deleteDisplayDesignElements,
  duplicateDisplayDesignElements,
  reorderDisplayDesignElement,
  type DisplayDesignDocumentV1,
} from './display-design-model'
import { compileDisplayDesign } from './display-design-compiler'
import { generateDisplayDesignLua } from './display-design-generator'
import { formatLuaNumber } from './display-design-resolution'

const openEngines: Array<Awaited<ReturnType<typeof createDistingLuaTestEngine>>> = []

afterEach(() => {
  for (const lua of openEngines.splice(0)) lua.global.close()
})

function everyPrimitiveDocument(displayMode: DisplayDesignDocumentV1['displayMode'] = 'full-screen'): DisplayDesignDocumentV1 {
  const ids = createSequentialDisplayDesignIdFactory('generated')
  const presets = [
    'pixel-line', 'smooth-line', 'outline-box', 'filled-box',
    'pixel-circle', 'smooth-circle', 'standard-text', 'tiny-text',
  ] as const
  const elements = presets.map((preset) => createDefaultDisplayPrimitive(preset, ids))
  const standardText = elements[6]
  if (standardText?.kind === 'text') standardText.text = { kind: 'literal', value: 'Quote " slash \\ newline\nGrüße' }
  const tinyText = elements[7]
  if (tinyText?.kind === 'text') {
    tinyText.text = { kind: 'literal', value: 'Fallback: \u{10ffff}' }
    tinyText.align = 'right'
  }
  return { ...createEmptyDisplayDesign('Generated vocabulary'), displayMode, elements }
}

async function runGenerated(document: DisplayDesignDocumentV1) {
  const generated = generateDisplayDesignLua(document)
  expect(generated.ok).toBe(true)
  if (!generated.ok) throw new Error('Expected generated source')
  const lua = await createDistingLuaTestEngine(50)
  openEngines.push(lua)
  const display = new DistingDisplayApi()
  display.register(lua.global)
  const runtime = await loadLuaProgramRuntime(lua, `return {\n${generated.source}}\n`)
  display.reset()
  const returned = runtime.draw?.()
  const commands = [...display.commands]
  runtime.close?.()
  return { commands, generated, returned, display }
}

describe('display design Lua generation', () => {
  it('generates deterministic readable source for static calls and safely quoted text', () => {
    const ids = createSequentialDisplayDesignIdFactory('golden')
    const box = createDefaultDisplayPrimitive('filled-box', ids)
    box.name = 'Meter\nframe'
    const text = createDefaultDisplayPrimitive('standard-text', ids)
    text.name = 'Quoted label'
    text.text = { kind: 'literal', value: 'Quote " slash \\ newline\n-- marker café \u0001' }
    text.align = 'centre'
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [box, text] }

    const first = generateDisplayDesignLua(document)
    const second = generateDisplayDesignLua(structuredClone(document))
    expect(first).toEqual(second)
    expect(first.ok).toBe(true)
    if (!first.ok) return
    expect(first.source).toBe(`draw = function(self)
  -- Generated by Luading Display designer; edit freely after copying.
  -- Meter frame
  drawRectangle(8, 16, 32, 24, 15)

  -- Quoted label
  drawText(8, 20, "Quote \\" slash \\\\ newline\\n-- marker café \\001", 15, "centre")

  return true
end,
`)
    expect(first.generatedUtf8Bytes).toBe(new TextEncoder().encode(first.source).byteLength)
  })

  it('emits binding locals once in document order with ordinary mapping and visibility expressions', () => {
    const ids = createSequentialDisplayDesignIdFactory('binding')
    const numberId = ids('binding')
    const booleanId = ids('binding')
    const textId = ids('binding')
    const line = createDefaultDisplayPrimitive('pixel-line', ids)
    line.x1 = { kind: 'number-binding', bindingId: numberId, from: 10, to: 30, quantize: 'integer' }
    line.shade = { kind: 'number-binding', bindingId: numberId, from: 0, to: 15, quantize: 'integer' }
    line.visible = { kind: 'boolean-binding', bindingId: booleanId, invert: true }
    const text = createDefaultDisplayPrimitive('tiny-text', ids)
    text.text = { kind: 'text-binding', bindingId: textId }
    const document: DisplayDesignDocumentV1 = {
      ...createEmptyDisplayDesign(),
      displayMode: 'full-screen',
      bindings: [
        { kind: 'number', id: numberId, name: 'Level', luaName: 'level', previewValue: 0.65 },
        { kind: 'boolean', id: booleanId, name: 'Muted', luaName: 'muted', previewValue: false },
        { kind: 'text', id: textId, name: 'Label', luaName: 'label', previewValue: 'Bound' },
      ],
      elements: [line, text],
    }
    const result = generateDisplayDesignLua(document)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain('local level = 0.65 -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('level = math.max(0.0, math.min(1.0, level))')
    expect(result.source).toContain('local muted = false -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('local label = "Bound" -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('if not muted then')
    expect(result.source).toContain('drawLine(math.floor((10 + 20 * level) + 0.5), 16, 32, 16, math.max(0, math.min(15, math.floor((15 * level) + 0.5))))')
    expect(result.source.match(/local level/g)).toHaveLength(1)
  })

  it('omits unused bindings with warnings and formats finite numbers without locale or binary-tail noise', () => {
    const document = everyPrimitiveDocument()
    document.bindings = [{ kind: 'number', id: 'unused', name: 'Unused', luaName: 'unused', previewValue: 0.1 }]
    const result = generateDisplayDesignLua(document)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.findings.map(({ ruleId }) => ruleId)).toContain('unused-binding')
    expect(result.source).not.toContain('local unused')
    expect(formatLuaNumber(-0)).toBe('0')
    expect(formatLuaNumber(0.1 + 0.2)).toBe('0.3')
    expect(formatLuaNumber(1234.56789012345)).toBe('1234.56789012')
  })

  it('uses exact callback return behavior for both display modes through Wasmoon', async () => {
    const parameterLine = await runGenerated(everyPrimitiveDocument('parameter-line'))
    expect(parameterLine.returned).not.toBe(true)
    expect(parameterLine.generated.source).not.toContain('return true')
    parameterLine.display.finish(parameterLine.returned === true, undefined, undefined)
    expect(parameterLine.display.commands.slice(0, 3)).toEqual([
      { kind: 'text', x: 2, y: 7, text: 'Lua Script', shade: 15, tiny: true, align: 'left' },
      { kind: 'text', x: 253, y: 7, text: '', shade: 15, tiny: true, align: 'right' },
      { kind: 'line', x1: 0, y1: 9, x2: 255, y2: 9, shade: 5, smooth: false },
    ])

    const fullScreen = await runGenerated(everyPrimitiveDocument('full-screen'))
    expect(fullScreen.returned).toBe(true)
    fullScreen.display.finish(fullScreen.returned === true, undefined, undefined)
    expect(fullScreen.display.commands).toEqual(fullScreen.commands)
  })

  it('matches compiler commands for every primitive, both fonts, escaping, reversed geometry, clipping, and shade-zero overdraw', async () => {
    const document = everyPrimitiveDocument()
    const line = document.elements[0]
    if (line?.kind === 'line') {
      line.x1 = { kind: 'literal', value: 300 }
      line.x2 = { kind: 'literal', value: -20 }
    }
    const box = document.elements[2]
    if (box?.kind === 'box') {
      box.x1 = { kind: 'literal', value: 40 }
      box.x2 = { kind: 'literal', value: 10 }
      box.shade = { kind: 'literal', value: 0 }
    }

    const compiler = compileDisplayDesign(document)
    const runtime = await runGenerated(document)
    expect(runtime.commands).toEqual(compiler.commands)
    expect(runtime.commands.map(({ kind }) => kind)).toEqual(['line', 'line', 'box', 'box', 'circle', 'circle', 'text', 'text'])
    expect(runtime.commands[2]).toMatchObject({ kind: 'box', x1: 40, x2: 10, shade: 0 })
  })

  it('matches compiler binding previews at multiple numeric, boolean, and text values through Wasmoon', async () => {
    for (const [index, previewValue] of [0, 0.3333333333333333, 1].entries()) {
      const ids = createSequentialDisplayDesignIdFactory(`preview-${index}`)
      const numberId = ids('binding')
      const booleanId = ids('binding')
      const textId = ids('binding')
      const smooth = createDefaultDisplayPrimitive('smooth-line', ids)
      smooth.x1 = { kind: 'number-binding', bindingId: numberId, from: -2.5, to: 10.75, quantize: 'none' }
      const text = createDefaultDisplayPrimitive('standard-text', ids)
      text.text = { kind: 'text-binding', bindingId: textId }
      text.visible = { kind: 'boolean-binding', bindingId: booleanId, invert: false }
      const document: DisplayDesignDocumentV1 = {
        ...createEmptyDisplayDesign(), displayMode: 'full-screen',
        bindings: [
          { kind: 'number', id: numberId, name: 'Position', luaName: 'position', previewValue },
          { kind: 'boolean', id: booleanId, name: 'Show label', luaName: 'show_label', previewValue: index !== 1 },
          { kind: 'text', id: textId, name: 'Label', luaName: 'label', previewValue: `State ${index}\n"quoted"` },
        ],
        elements: [smooth, text],
      }

      const compiler = compileDisplayDesign(document)
      const runtime = await runGenerated(document)
      expect(runtime.commands).toEqual(compiler.commands)
    }
  })

  it('keeps generated output equivalent after immutable duplicate, reorder, and delete operations', async () => {
    const ids = createSequentialDisplayDesignIdFactory('operations')
    let document: DisplayDesignDocumentV1 = {
      ...createEmptyDisplayDesign(), displayMode: 'full-screen',
      elements: [
        createDefaultDisplayPrimitive('pixel-line', ids),
        createDefaultDisplayPrimitive('filled-box', ids),
        createDefaultDisplayPrimitive('tiny-text', ids),
      ],
    }
    const duplicated = duplicateDisplayDesignElements(document, [document.elements[0]!.id], ids)
    document = reorderDisplayDesignElement(duplicated.document, 0, duplicated.document.elements.length - 1)
    document = deleteDisplayDesignElements(document, [document.elements[1]!.id])

    const compiler = compileDisplayDesign(document)
    const runtime = await runGenerated(document)
    expect(runtime.commands).toEqual(compiler.commands)
    expect(runtime.commands).toHaveLength(3)
  })

  it('blocks invalid documents and symbol instances from producing partial source', () => {
    const invalid = everyPrimitiveDocument()
    invalid.displayMode = 'invalid' as DisplayDesignDocumentV1['displayMode']
    expect(generateDisplayDesignLua(invalid)).toMatchObject({ ok: false, source: '', generatedUtf8Bytes: 0 })

    const withInstance = everyPrimitiveDocument()
    withInstance.elements.push({
      kind: 'symbol-instance', id: 'instance', name: 'Instance', symbolId: 'missing',
      x: { kind: 'literal', value: 0 }, y: { kind: 'literal', value: 0 },
      visible: { kind: 'visible' }, state: { kind: 'literal', variantId: 'missing' },
    })
    const result = generateDisplayDesignLua(withInstance)
    expect(result.ok).toBe(false)
    expect(result.findings.map(({ ruleId }) => ruleId)).toContain('dangling-symbol')
  })
})
