import { afterEach, describe, expect, it } from 'vitest'
import { DistingDisplayApi } from '../../emulation/display-api'
import { loadLuaProgramRuntime } from '../../emulation/lua-runtime'
import { createDistingLuaTestEngine } from '../../testing/lua-test-environment'
import {
  addDisplayDesignElement,
  addDisplayDesignScreen,
  createDefaultDisplayPrimitive,
  createEmptyDisplayDesign,
  createSequentialDisplayDesignIdFactory,
  deleteDisplayDesignElements,
  duplicateDisplayDesignElements,
  reorderDisplayDesignElement,
  type DisplayDesignDocument,
} from './display-design-model'
import { compileDisplayDesign } from './display-design-compiler'
import { generateDisplayDesignLua } from './display-design-generator'
import { formatLuaNumber } from './display-design-resolution'
import {
  addDisplaySymbolVariant,
  createDisplaySymbolFromSelection,
  makeDisplaySymbolStateDynamic,
  updateDisplaySymbolVariant,
} from './display-design-symbols'

const openEngines: Array<Awaited<ReturnType<typeof createDistingLuaTestEngine>>> = []

afterEach(() => {
  for (const lua of openEngines.splice(0)) lua.global.close()
})

function everyPrimitiveDocument(displayMode: DisplayDesignDocument['displayMode'] = 'full-screen'): DisplayDesignDocument {
  const ids = createSequentialDisplayDesignIdFactory('generated')
  const presets = [
    'pixel-line', 'smooth-line', 'outline-box', 'filled-box',
    'pixel-circle', 'smooth-circle', 'standard-text', 'tiny-text',
  ] as const
  const elements = presets.map((preset) => createDefaultDisplayPrimitive(preset, ids))
  const standardText = elements[6]
  if (standardText?.kind === 'text') standardText.text = { kind: 'literal', value: 'Quote " slash \\ newline\nGrüße' }
  const tinyText = elements[7]
  if (tinyText?.kind === 'text') {
    tinyText.text = { kind: 'literal', value: 'Fallback: \u{10ffff}' }
    tinyText.align = 'right'
  }
  return { ...createEmptyDisplayDesign('Generated vocabulary'), displayMode, elements }
}

async function runGenerated(document: DisplayDesignDocument) {
  const generated = generateDisplayDesignLua(document)
  expect(generated.ok).toBe(true)
  if (!generated.ok) throw new Error('Expected generated source')
  const lua = await createDistingLuaTestEngine(50)
  openEngines.push(lua)
  const display = new DistingDisplayApi()
  display.register(lua.global)
  const runtime = await loadLuaProgramRuntime(lua, `return {\n${generated.source}}\n`)
  display.reset()
  const returned = runtime.draw?.()
  const commands = [...display.commands]
  runtime.close?.()
  return { commands, generated, returned, display }
}

describe('display design Lua generation', () => {
  it('branches named screens through one collision-safe selector in the draw callback', () => {
    const ids = createSequentialDisplayDesignIdFactory('screens')
    const first = addDisplayDesignElement(
      createEmptyDisplayDesign('Pages'),
      createDefaultDisplayPrimitive('pixel-line', ids),
    )
    const second = addDisplayDesignScreen(first, ids, 'Settings')
    const document = addDisplayDesignElement(
      second.document,
      createDefaultDisplayPrimitive('standard-text', ids),
    )
    document.bindings = [{ kind: 'text', id: ids('binding'), name: 'Collision', luaName: 'screen', previewValue: 'Text' }]

    const generated = generateDisplayDesignLua(document)
    expect(generated.ok).toBe(true)
    if (!generated.ok) return
    expect(generated.source).toContain('local screen_2 = 2 -- TODO: connect this screen selector to self or a parameter.')
    expect(generated.source).toContain('if screen_2 == 1 then\n      -- Screen 1: Screen 1')
    expect(generated.source).toContain('elseif screen_2 == 2 then\n      -- Screen 2: Settings')
    expect(generated.source).toContain('drawLine(8, 16, 32, 16, 15)')
    expect(generated.source).toContain('drawText(8, 20, "Text", 15, "left")')
  })

  it('generates deterministic readable source for static calls and safely quoted text', () => {
    const ids = createSequentialDisplayDesignIdFactory('golden')
    const box = createDefaultDisplayPrimitive('filled-box', ids)
    box.name = 'Meter\nframe'
    const text = createDefaultDisplayPrimitive('standard-text', ids)
    text.name = 'Quoted label'
    text.text = { kind: 'literal', value: 'Quote " slash \\ newline\n-- marker café \u0001' }
    text.align = 'centre'
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [box, text] }

    const first = generateDisplayDesignLua(document)
    const second = generateDisplayDesignLua(structuredClone(document))
    expect(first).toEqual(second)
    expect(first.ok).toBe(true)
    if (!first.ok) return
    expect(first.source).toBe(`draw = function(self)
  -- Generated by Luading Display designer; edit freely after copying.
  -- Meter frame
  drawRectangle(8, 16, 32, 24, 15)

  -- Quoted label
  drawText(8, 20, "Quote \\" slash \\\\ newline\\n-- marker café \\001", 15, "centre")

  return true
end,
`)
    expect(first.generatedUtf8Bytes).toBe(new TextEncoder().encode(first.source).byteLength)
  })

  it('keeps layout-grid authoring metadata out of generated Lua', () => {
    const document = everyPrimitiveDocument()
    const withoutGrid = generateDisplayDesignLua(document)
    const withGrid = generateDisplayDesignLua({
      ...document,
      layoutGrid: { kind: 'uniform', size: 8, color: '#ff0000', opacity: 10 },
    })

    expect(withGrid).toEqual(withoutGrid)
  })

  it('runs optimized pixel-box Lua through the real Lua/display boundary', async () => {
    const ids = createSequentialDisplayDesignIdFactory('pixel-box')
    const pixelBox = createDefaultDisplayPrimitive('pixel-box', ids)
    pixelBox.width = 3
    pixelBox.height = 3
    pixelBox.frames[0]!.shades = [3, 3, 3, 3, 8, 3, 3, 3, 3]
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [pixelBox] }
    const { commands, generated } = await runGenerated(document)

    expect(generated.source).toContain('drawRectangle(8, 16, 8 + 2, 16 + 2, 3)')
    expect(generated.source).toContain('drawLine(8 + 1, 16 + 1, 8 + 1, 16 + 1, 8)')
    expect(commands).toEqual(compileDisplayDesign(document).commands)
  })

  it('runs pixel-box animation on 30 Hz draw callbacks through the real Lua boundary', async () => {
    const ids = createSequentialDisplayDesignIdFactory('animated-pixel-box')
    const pixelBox = createDefaultDisplayPrimitive('pixel-box', ids)
    pixelBox.width = 1
    pixelBox.height = 1
    pixelBox.frameRate = 15
    pixelBox.frames = [{ shades: [3], duration: 2 }, { shades: [11], duration: 1 }]
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [pixelBox] }
    const generated = generateDisplayDesignLua(document)
    expect(generated.ok).toBe(true)
    if (!generated.ok) return
    expect(generated.source).toContain('local displayFrame = 0')
    expect(generated.source).toContain('if displayFrame % 6 < 4 then')
    expect(generated.source).toContain('elseif displayFrame % 6 < 6 then')

    const lua = await createDistingLuaTestEngine(50)
    openEngines.push(lua)
    const display = new DistingDisplayApi()
    display.register(lua.global)
    const runtime = await loadLuaProgramRuntime(lua, `return {\n${generated.source}}\n`)
    const shades = Array.from({ length: 7 }, () => {
      display.reset()
      runtime.draw?.()
      const command = display.commands[0]
      return command && 'shade' in command ? command.shade : undefined
    })
    runtime.close?.()

    expect(shades).toEqual([3, 3, 3, 3, 11, 11, 3])
  })

  it('runs animated lines through one custom helper at the real Lua/display boundary', async () => {
    const ids = createSequentialDisplayDesignIdFactory('animated-line')
    const line = createDefaultDisplayPrimitive('animated-line', ids)
    line.x1 = { kind: 'literal', value: 0 }
    line.y1 = { kind: 'literal', value: 12 }
    line.x2 = { kind: 'literal', value: 11 }
    line.y2 = { kind: 'literal', value: 12 }
    line.secondaryShade = { kind: 'literal', value: 3 }
    line.speed = 15
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [line] }
    const generated = generateDisplayDesignLua(document)
    expect(generated.ok).toBe(true)
    if (!generated.ok) return
    expect(generated.source).toContain('local function drawAnimatedLine(x1, y1, x2, y2, primaryShade, secondaryShade, direction, speed, frame)')
    expect(generated.source).toContain('drawAnimatedLine(0, 12, 11, 12, 15, 3, "right", 15, displayFrame)')
    expect(generated.source.match(/local function drawAnimatedLine/g)).toHaveLength(1)

    const lua = await createDistingLuaTestEngine(50)
    openEngines.push(lua)
    const display = new DistingDisplayApi()
    display.register(lua.global)
    const runtime = await loadLuaProgramRuntime(lua, `return {\n${generated.source}}\n`)
    for (const frame of [0, 1, 2]) {
      display.reset()
      runtime.draw?.()
      expect(display.commands).toEqual(compileDisplayDesign(document, frame).commands)
    }
    runtime.close?.()
  })

  it('runs polygons through one minimal reusable Lua helper at the real display boundary', async () => {
    const ids = createSequentialDisplayDesignIdFactory('polygon')
    const polygon = createDefaultDisplayPrimitive('polygon', ids)
    polygon.sides = 4
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [polygon] }
    const { commands, generated } = await runGenerated(document)

    expect(generated.source).toContain('local function drawPolygon(x, y, radius, sides, shade)')
    expect(generated.source).toContain('drawPolygon(20, 20, 8, 4, 15)')
    expect(generated.source.match(/local function drawPolygon/g)).toHaveLength(1)
    expect(commands).toEqual(compileDisplayDesign(document).commands)
  })

  it('runs multi-point Béziers through one minimal reusable Lua helper at the real display boundary', async () => {
    const ids = createSequentialDisplayDesignIdFactory('bezier')
    const bezier = createDefaultDisplayPrimitive('bezier', ids)
    bezier.segments = 7
    const document = { ...createEmptyDisplayDesign(), displayMode: 'full-screen' as const, elements: [bezier] }
    const { commands, generated } = await runGenerated(document)

    expect(generated.source).toContain('local function drawBezier(points, segments, shade)')
    expect(generated.source).toContain('drawBezier({{8, 24}, {20, 12}, {36, 36}, {48, 24}}, 7, 15)')
    expect(generated.source.match(/local function drawBezier/g)).toHaveLength(1)
    expect(commands).toEqual(compileDisplayDesign(document).commands)
  })

  it('emits binding locals once in document order with ordinary mapping and visibility expressions', () => {
    const ids = createSequentialDisplayDesignIdFactory('binding')
    const numberId = ids('binding')
    const booleanId = ids('binding')
    const textId = ids('binding')
    const line = createDefaultDisplayPrimitive('pixel-line', ids)
    line.x1 = { kind: 'number-binding', bindingId: numberId, from: { kind: 'literal', value: 10 }, to: { kind: 'literal', value: 30 }, quantize: 'integer' }
    line.shade = { kind: 'number-binding', bindingId: numberId, from: { kind: 'literal', value: 0 }, to: { kind: 'literal', value: 15 }, quantize: 'integer' }
    line.visible = { kind: 'boolean-binding', bindingId: booleanId, invert: true }
    const text = createDefaultDisplayPrimitive('tiny-text', ids)
    text.text = { kind: 'text-binding', bindingId: textId }
    const document: DisplayDesignDocument = {
      ...createEmptyDisplayDesign(),
      displayMode: 'full-screen',
      bindings: [
        { kind: 'number', id: numberId, name: 'Level', luaName: 'level', previewValue: 0.65 },
        { kind: 'boolean', id: booleanId, name: 'Muted', luaName: 'muted', previewValue: false },
        { kind: 'text', id: textId, name: 'Label', luaName: 'label', previewValue: 'Bound' },
      ],
      elements: [line, text],
    }
    const result = generateDisplayDesignLua(document)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain('local level = 0.65 -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('level = math.max(0.0, math.min(1.0, level))')
    expect(result.source).toContain('local muted = false -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('local label = "Bound" -- TODO: connect this placeholder to self or a parameter.')
    expect(result.source).toContain('if not muted then')
    expect(result.source).toContain('drawLine(math.floor((10 + 20 * level) + 0.5), 16, 32, 16, math.max(0, math.min(15, math.floor((15 * level) + 0.5))))')
    expect(result.source.match(/local level/g)).toHaveLength(1)
  })

  it('emits reachable token locals in document order and matches compiler arithmetic through Wasmoon', async () => {
    for (const previewValue of [0, 0.5, 1]) {
      const ids = createSequentialDisplayDesignIdFactory(`tokens-${previewValue}`)
      const tokens = [
        { id: ids('token'), name: 'Start X', luaName: 'start_x', value: 8 },
        { id: ids('token'), name: 'Bar width', luaName: 'bar_width', value: 12 },
        { id: ids('token'), name: 'Bars Y', luaName: 'bars_y', value: 18 },
        { id: ids('token'), name: 'Unused', luaName: 'unused_token', value: 99 },
      ]
      const numberId = ids('binding')
      const box = createDefaultDisplayPrimitive('filled-box', ids)
      box.x1 = { kind: 'token-expression', expression: { kind: 'token', tokenId: tokens[0]!.id } }
      box.x2 = { kind: 'token-expression', expression: {
        kind: 'binary', operator: 'subtract',
        left: { kind: 'binary', operator: 'add', left: { kind: 'token', tokenId: tokens[0]!.id }, right: { kind: 'token', tokenId: tokens[1]!.id } },
        right: { kind: 'number', value: 1 },
      } }
      box.y1 = { kind: 'number-binding', bindingId: numberId, from: { kind: 'token-expression', expression: { kind: 'token', tokenId: tokens[2]!.id } }, to: { kind: 'token-expression', expression: { kind: 'binary', operator: 'add', left: { kind: 'token', tokenId: tokens[2]!.id }, right: { kind: 'number', value: 6 } } }, quantize: 'integer' }
      const document: DisplayDesignDocument = {
        ...createEmptyDisplayDesign(), displayMode: 'full-screen', tokens, elements: [box],
        bindings: [{ kind: 'number', id: numberId, name: 'Height', luaName: 'height', previewValue }],
      }
      const compiled = compileDisplayDesign(document)
      const runtime = await runGenerated(document)
      expect(runtime.commands).toEqual(compiled.commands)
      expect(runtime.generated.source).toContain('-- Design tokens: change these values to fine-tune the layout.')
      expect(runtime.generated.source.indexOf('local start_x = 8')).toBeLessThan(runtime.generated.source.indexOf('local bar_width = 12'))
      expect(runtime.generated.source).not.toContain('local unused_token')
      expect(runtime.generated.findings.map(({ ruleId }) => ruleId)).toContain('unused-token')
      expect(runtime.generated.tokenLocations[tokens[0]!.id]?.line).toBe(3)
    }
  })

  it('keeps tokenized symbol helpers shared and token renames source-only', async () => {
    const ids = createSequentialDisplayDesignIdFactory('token-symbol')
    const primitive = createDefaultDisplayPrimitive('filled-box', ids)
    let document: DisplayDesignDocument = { ...createEmptyDisplayDesign(), elements: [primitive] }
    const created = createDisplaySymbolFromSelection(document, [primitive.id], ids, { name: 'Bar' })
    document = created.document
    const token = { id: ids('token'), name: 'Offset', luaName: 'bar_offset', value: 4 }
    document.tokens = [token]
    const symbol = document.symbols[0]!
    const stored = symbol.variants[0]!.elements[0]!
    if (stored.kind !== 'box') throw new Error('Expected box')
    stored.x1 = { kind: 'token-expression', expression: { kind: 'token', tokenId: token.id } }
    document.elements.push(structuredClone(created.instance!))
    document.elements[1]!.id = ids('element')
    const before = await runGenerated(document)
    const renamed = structuredClone(document)
    renamed.tokens[0] = { ...token, name: 'Inset', luaName: 'bar_inset' }
    const after = await runGenerated(renamed)
    expect(before.commands).toEqual(after.commands)
    expect(before.generated.source).toContain('local bar_offset = 4')
    expect(after.generated.source).toContain('local bar_inset = 4')
    expect(after.generated.source.match(/local function draw_bar\(/g)).toHaveLength(1)
    expect(after.generated.source.match(/draw_bar\(/g)).toHaveLength(3)
  })

  it('omits unused bindings with warnings and formats finite numbers without locale or binary-tail noise', () => {
    const document = everyPrimitiveDocument()
    document.bindings = [{ kind: 'number', id: 'unused', name: 'Unused', luaName: 'unused', previewValue: 0.1 }]
    const result = generateDisplayDesignLua(document)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.findings.map(({ ruleId }) => ruleId)).toContain('unused-binding')
    expect(result.source).not.toContain('local unused')
    expect(formatLuaNumber(-0)).toBe('0')
    expect(formatLuaNumber(0.1 + 0.2)).toBe('0.3')
    expect(formatLuaNumber(1234.56789012345)).toBe('1234.56789012')
  })

  it('uses exact callback return behavior for both display modes through Wasmoon', async () => {
    const parameterLine = await runGenerated(everyPrimitiveDocument('parameter-line'))
    expect(parameterLine.returned).not.toBe(true)
    expect(parameterLine.generated.source).not.toContain('return true')
    parameterLine.display.finish(parameterLine.returned === true, undefined, undefined)
    expect(parameterLine.display.commands.slice(0, 3)).toEqual([
      { kind: 'text', x: 2, y: 7, text: 'Lua Script', shade: 15, tiny: true, align: 'left' },
      { kind: 'text', x: 253, y: 7, text: '', shade: 15, tiny: true, align: 'right' },
      { kind: 'line', x1: 0, y1: 9, x2: 255, y2: 9, shade: 5, smooth: false },
    ])

    const fullScreen = await runGenerated(everyPrimitiveDocument('full-screen'))
    expect(fullScreen.returned).toBe(true)
    fullScreen.display.finish(fullScreen.returned === true, undefined, undefined)
    expect(fullScreen.display.commands).toEqual(fullScreen.commands)
  })

  it('matches compiler commands for every primitive, both fonts, escaping, reversed geometry, clipping, and shade-zero overdraw', async () => {
    const document = everyPrimitiveDocument()
    const line = document.elements[0]
    if (line?.kind === 'line') {
      line.x1 = { kind: 'literal', value: 300 }
      line.x2 = { kind: 'literal', value: -20 }
    }
    const box = document.elements[2]
    if (box?.kind === 'box') {
      box.x1 = { kind: 'literal', value: 40 }
      box.x2 = { kind: 'literal', value: 10 }
      box.shade = { kind: 'literal', value: 0 }
    }

    const compiler = compileDisplayDesign(document)
    const runtime = await runGenerated(document)
    expect(runtime.commands).toEqual(compiler.commands)
    expect(runtime.commands.map(({ kind }) => kind)).toEqual(['line', 'line', 'box', 'box', 'circle', 'circle', 'text', 'text'])
    expect(runtime.commands[2]).toMatchObject({ kind: 'box', x1: 40, x2: 10, shade: 0 })
  })

  it('matches compiler binding previews at multiple numeric, boolean, and text values through Wasmoon', async () => {
    for (const [index, previewValue] of [0, 0.3333333333333333, 1].entries()) {
      const ids = createSequentialDisplayDesignIdFactory(`preview-${index}`)
      const numberId = ids('binding')
      const booleanId = ids('binding')
      const textId = ids('binding')
      const smooth = createDefaultDisplayPrimitive('smooth-line', ids)
      smooth.x1 = { kind: 'number-binding', bindingId: numberId, from: { kind: 'literal', value: -2.5 }, to: { kind: 'literal', value: 10.75 }, quantize: 'none' }
      const text = createDefaultDisplayPrimitive('standard-text', ids)
      text.text = { kind: 'text-binding', bindingId: textId }
      text.visible = { kind: 'boolean-binding', bindingId: booleanId, invert: false }
      const document: DisplayDesignDocument = {
        ...createEmptyDisplayDesign(), displayMode: 'full-screen',
        bindings: [
          { kind: 'number', id: numberId, name: 'Position', luaName: 'position', previewValue },
          { kind: 'boolean', id: booleanId, name: 'Show label', luaName: 'show_label', previewValue: index !== 1 },
          { kind: 'text', id: textId, name: 'Label', luaName: 'label', previewValue: `State ${index}\n"quoted"` },
        ],
        elements: [smooth, text],
      }

      const compiler = compileDisplayDesign(document)
      const runtime = await runGenerated(document)
      expect(runtime.commands).toEqual(compiler.commands)
    }
  })

  it('keeps generated output equivalent after immutable duplicate, reorder, and delete operations', async () => {
    const ids = createSequentialDisplayDesignIdFactory('operations')
    let document: DisplayDesignDocument = {
      ...createEmptyDisplayDesign(), displayMode: 'full-screen',
      elements: [
        createDefaultDisplayPrimitive('pixel-line', ids),
        createDefaultDisplayPrimitive('filled-box', ids),
        createDefaultDisplayPrimitive('tiny-text', ids),
      ],
    }
    const duplicated = duplicateDisplayDesignElements(document, [document.elements[0]!.id], ids)
    document = reorderDisplayDesignElement(duplicated.document, 0, duplicated.document.elements.length - 1)
    document = deleteDisplayDesignElements(document, [document.elements[1]!.id])

    const compiler = compileDisplayDesign(document)
    const runtime = await runGenerated(document)
    expect(runtime.commands).toEqual(compiler.commands)
    expect(runtime.commands).toHaveLength(3)
  })

  it('emits one shared helper outside draw and matches compiler expansion for literal and choice states', async () => {
    const ids = createSequentialDisplayDesignIdFactory('symbol-runtime')
    const box = createDefaultDisplayPrimitive('outline-box', ids)
    box.x1 = { kind: 'literal', value: 0 }
    box.y1 = { kind: 'literal', value: 0 }
    box.x2 = { kind: 'literal', value: 8 }
    box.y2 = { kind: 'literal', value: 6 }
    let document: DisplayDesignDocument = { ...createEmptyDisplayDesign(), displayMode: 'full-screen', elements: [box] }
    const created = createDisplaySymbolFromSelection(document, [box.id], ids, { name: 'Status', origin: { x: 0, y: 0 } })
    const added = addDisplaySymbolVariant(created.document, created.symbol!.id, ids, { name: 'Active' })
    document = updateDisplaySymbolVariant(added.document, created.symbol!.id, added.variantId!, (variant) => {
      const fill = createDefaultDisplayPrimitive('filled-box', ids, 'primitive')
      fill.x1 = { kind: 'literal', value: 1 }; fill.y1 = { kind: 'literal', value: 1 }
      fill.x2 = { kind: 'literal', value: 7 }; fill.y2 = { kind: 'literal', value: 5 }
      return { ...variant, elements: [...variant.elements, fill] }
    })
    const first = document.elements[0]!
    if (first.kind !== 'symbol-instance') throw new Error('Expected instance')
    first.x = { kind: 'literal', value: 10 }
    first.y = { kind: 'literal', value: 12 }
    const duplicated = duplicateDisplayDesignElements(document, [first.id], ids)
    document = duplicated.document
    const second = document.elements[1]!
    if (second.kind !== 'symbol-instance') throw new Error('Expected duplicate instance')
    second.x = { kind: 'literal', value: 40 }
    second.y = { kind: 'literal', value: 20 }
    second.state = { kind: 'literal', variantId: added.variantId! }
    const dynamic = makeDisplaySymbolStateDynamic(document, first.id, ids)
    document = dynamic.document

    for (const choice of dynamic.binding!.choices) {
      const selected = structuredClone(document)
      const binding = selected.bindings.find(({ id }) => id === dynamic.binding!.id)
      if (binding?.kind === 'choice') binding.previewChoiceId = choice.id
      const compiled = compileDisplayDesign(selected)
      const runtime = await runGenerated(selected)
      expect(runtime.commands).toEqual(compiled.commands)
      expect(compiled.metrics.maximumVariantDrawCallCount).toBe(4)
    }

    const generated = generateDisplayDesignLua(document)
    expect(generated.ok).toBe(true)
    if (!generated.ok) return
    expect(generated.source.match(/local function draw_status\(/g)).toHaveLength(1)
    const helperIndex = generated.source.indexOf('local function draw_status')
    const returnedDrawIndex = generated.source.indexOf('return function(self)')
    expect(helperIndex).toBeGreaterThan(generated.source.indexOf('draw = (function()'))
    expect(helperIndex).toBeLessThan(returnedDrawIndex)
    expect(generated.source).toContain('else\n      -- Default state: Default')
    expect(generated.source.match(/draw_status\(/g)).toHaveLength(3)
  })

  it('uses the declared default for unknown runtime state and keeps repeated draw callbacks stable', async () => {
    const ids = createSequentialDisplayDesignIdFactory('unknown-state')
    const line = createDefaultDisplayPrimitive('pixel-line', ids)
    line.x1 = { kind: 'literal', value: 0 }; line.y1 = { kind: 'literal', value: 0 }
    line.x2 = { kind: 'literal', value: 4 }; line.y2 = { kind: 'literal', value: 0 }
    const created = createDisplaySymbolFromSelection({ ...createEmptyDisplayDesign(), displayMode: 'full-screen', elements: [line] }, [line.id], ids)
    const added = addDisplaySymbolVariant(created.document, created.symbol!.id, ids, { blank: true, name: 'Active' })
    const dynamic = makeDisplaySymbolStateDynamic(added.document, created.instance!.id, ids)
    const generated = generateDisplayDesignLua(dynamic.document)
    expect(generated.ok).toBe(true)
    if (!generated.ok) return
    const previewValue = dynamic.binding!.choices[0]!.luaValue
    const source = generated.source.replace(
      `${dynamic.binding!.luaName} = ${JSON.stringify(previewValue)} -- TODO: choose this state from self or parameters.`,
      `${dynamic.binding!.luaName} = "unknown" -- TODO: choose this state from self or parameters.`,
    )
    const lua = await createDistingLuaTestEngine(50)
    openEngines.push(lua)
    const display = new DistingDisplayApi()
    display.register(lua.global)
    const runtime = await loadLuaProgramRuntime(lua, `return {\n${source}}\n`)
    display.reset(); runtime.draw?.()
    const first = [...display.commands]
    display.reset(); runtime.draw?.()
    expect(display.commands).toEqual(first)
    expect(first).toEqual([{ kind: 'line', x1: 0, y1: 0, x2: 4, y2: 0, shade: 15, smooth: false }])
    runtime.close?.()
  })

  it('blocks invalid documents and symbol instances from producing partial source', () => {
    const invalid = everyPrimitiveDocument()
    invalid.displayMode = 'invalid' as DisplayDesignDocument['displayMode']
    expect(generateDisplayDesignLua(invalid)).toMatchObject({ ok: false, source: '', generatedUtf8Bytes: 0 })

    const withInstance = everyPrimitiveDocument()
    withInstance.elements.push({
      kind: 'symbol-instance', id: 'instance', name: 'Instance', symbolId: 'missing',
      x: { kind: 'literal', value: 0 }, y: { kind: 'literal', value: 0 },
      visible: { kind: 'visible' }, state: { kind: 'literal', variantId: 'missing' },
    })
    const result = generateDisplayDesignLua(withInstance)
    expect(result.ok).toBe(false)
    expect(result.findings.map(({ ruleId }) => ruleId)).toContain('dangling-symbol')
  })
})
