-- Build a single-file ntlib bundle with package.preload entries.
-- Usage: lua tools/amalgamate.lua volts quant clock gate > ntlib-single.lua
local dependencies = {
  num = {}, rand = { "num" }, gate = {}, state = {}, test = {},
  volts = {}, signal = { "num" }, clock = { "num" }, env = { "num" },
  param = { "num" }, draw = { "num" }, lfo = { "num", "volts", "rand" },
  quant = { "num" }, theory = { "quant" }, midi = { "num", "volts", "clock" },
  rhythm = { "num", "rand" }, seq = { "num", "rand" },
}
local all = { "num", "volts", "quant", "signal", "clock", "gate", "env", "lfo", "rand", "rhythm", "seq", "theory", "param", "state", "midi", "draw" }
local requested = {}
for i = 1, #arg do requested[#requested + 1] = arg[i] end
if #requested == 0 or (#requested == 1 and requested[1] == "full") then requested = all end
local ordered, visited, visiting = {}, {}, {}
local function visit(name)
  if visited[name] then return end
  if visiting[name] then error("dependency cycle at " .. name) end
  if not dependencies[name] then error("unknown ntlib module: " .. name) end
  visiting[name] = true
  for _, dependency in ipairs(dependencies[name]) do visit(dependency) end
  visiting[name], visited[name] = nil, true
  ordered[#ordered + 1] = name
end
for _, name in ipairs(requested) do visit(name) end
local function read(path) local file = assert(io.open(path, "rb")); local source = assert(file:read("a")); file:close(); return source end
io.write("-- ntlib single-file bundle; generated by tools/amalgamate.lua\n")
io.write("package.preload[\"ntlib\"] = function(...)\n", read("src/ntlib/init.lua"), "\nend\n")
for _, name in ipairs(ordered) do io.write("package.preload[\"ntlib.", name, "\"] = function(...)\n", read("src/ntlib/" .. name .. ".lua"), "\nend\n") end
io.write("return require \"ntlib\"\n")
