local num = require "ntlib.num"
local M = { W = 256, H = 64, TOP = 10, grey = { off = 0, faint = 2, dim = 5, mid = 8, bright = 12, full = 15 } }
local tinyWidths = { [" "] = 3, ["I"] = 2, ["i"] = 2, ["l"] = 2, ["."] = 2, [":"] = 2, ["1"] = 4 }
local normalWidths = { [" "] = 4, ["I"] = 3, ["i"] = 2, ["l"] = 3, ["."] = 3, [":"] = 3, ["1"] = 5 }
local function fontName(font) if font == "tiny" then return "tiny" elseif font == "smart" then return "smart" end return "normal" end
function M.textWidth(text, font) local widths, fallback = fontName(font) == "tiny" and tinyWidths or normalWidths, fontName(font) == "tiny" and 4 or 6; local total = 0; text = tostring(text); for i = 1, #text do total = total + (widths[text:sub(i, i)] or fallback) end return math.max(0, total - 1) end
function M.fontHeight(font) if fontName(font) == "tiny" then return 6 end return 8 end
function M.centreX(text, font) return math.floor((M.W - M.textWidth(text, font)) * 0.5 + 0.5) end
function M.rows(n, top, gap, out) out = out or {}; top, gap = top or M.TOP, gap or 0; local height = (M.H - top - gap * (n - 1)) / n; for i = 1, n do out[i] = math.floor(top + (i - 1) * (height + gap) + 0.5) end return out end
function M.cols(n, left, right, gap, out) out = out or {}; left, right, gap = left or 0, right or M.W - 1, gap or 0; local width = (right - left - gap * (n - 1)) / n; for i = 1, n do out[i] = math.floor(left + (i - 1) * (width + gap) + 0.5) end return out end
local function textFn(font) if fontName(font) == "tiny" then return drawTinyText end return drawText end
function M.label(x, y, text, colour, align, font) textFn(font)(x, y, tostring(text), colour or 15, align == "left" and nil or align); return M end
function M.value(x, y, label, value, colour) value, label = tostring(value), tostring(label); drawText(x - M.textWidth(value) - M.textWidth(label) - 6, y, label, M.grey.dim); drawText(x, y, value, colour or M.grey.full, "right"); return M end
function M.marquee(x, y, width, text, phase, colour, font) local tw = M.textWidth(text, font); local offset = tw <= width and 0 or math.floor((tw - width) * num.clamp(phase or 0, 0, 1)); textFn(font)(x - offset, y, tostring(text), colour or 15); return M end
function M.frame(x, y, w, h, colour) drawBox(x, y, x + w - 1, y + h - 1, colour or M.grey.mid); return M end
function M.hline(y, x1, x2, colour) drawLine(x1, y, x2, y, colour or M.grey.mid); return M end
function M.vline(x, y1, y2, colour) drawLine(x, y1, x, y2, colour or M.grey.mid); return M end
function M.dither(x, y, w, h, level) level = num.clamp(math.floor(level or 1), 0, 4); if level == 0 then return M end; for yy = y, y + h - 1 do for xx = x, x + w - 1 do if (xx + yy) % (5 - level) == 0 then drawRectangle(xx, yy, xx, yy, M.grey.dim) end end end return M end
function M.bar(x, y, w, h, value, opts) opts = opts or {}; local colour = opts.colour or M.grey.bright; M.frame(x, y, w, h, opts.frame or M.grey.dim); local fill = math.floor(num.clamp(value, 0, 1) * math.max(0, w - 2) + 0.5); if fill > 0 then drawRectangle(x + 1, y + 1, x + fill, y + h - 2, colour) end return M end
function M.meter(x, y, w, h, voltage, opts) opts = opts or {}; if opts.bipolar then local center = x + math.floor(w * 0.5); M.frame(x, y, w, h, opts.frame or M.grey.dim); local amount = num.clamp(voltage / (opts.max or 10), -1, 1); local edge = center + math.floor(amount * (w * 0.5 - 1)); drawRectangle(math.min(center, edge), y + 1, math.max(center, edge), y + h - 2, opts.colour or M.grey.bright); return M end return M.bar(x, y, w, h, voltage / (opts.max or 10), opts) end
function M.slider(x, y, w, h, value, opts) opts = opts or {}; M.frame(x, y, w, h, opts.frame or M.grey.dim); local hx = x + 1 + math.floor(num.clamp(value, 0, 1) * math.max(0, w - 3)); drawRectangle(hx, y + 1, hx, y + h - 2, opts.colour or M.grey.full); return M end
function M.knob(cx, cy, radius, value, opts) opts = opts or {}; local start, sweep = (opts.start or 0.625) * 2 * math.pi, (opts.sweep or 0.75) * 2 * math.pi; drawCircle(cx, cy, radius, opts.frame or M.grey.dim); local angle = start + num.clamp(value, 0, 1) * sweep; drawLine(cx, cy, cx + math.floor(math.cos(angle) * (radius - 1) + 0.5), cy + math.floor(math.sin(angle) * (radius - 1) + 0.5), opts.colour or M.grey.full); return M end
function M.gauge(x, y, w, h, value, opts) opts = opts or {}; local segments = math.max(1, math.floor(opts.segments or 8)); local active = math.floor(num.clamp(value, 0, 1) * segments + 0.5); local sw = math.max(1, math.floor((w - segments + 1) / segments)); for i = 1, segments do local sx = x + (i - 1) * (sw + 1); drawRectangle(sx, y, math.min(x + w - 1, sx + sw - 1), y + h - 1, i <= active and (opts.colour or M.grey.bright) or (opts.off or M.grey.faint)) end return M end
function M.scope(x, y, w, h, buffer, opts) opts = opts or {}; local count = math.min(buffer.filled or buffer.size or 0, w); if count < 1 then return M end; local lo, hi = opts.min or buffer:min() or -1, opts.max or buffer:max() or 1; if hi == lo then hi = lo + 1 end; local previousX, previousY; for px = 0, count - 1 do local sample = buffer:atIndex(count - px); local py = y + h - 1 - math.floor(num.clamp((sample - lo) / (hi - lo), 0, 1) * (h - 1) + 0.5); local xx = x + math.floor(px * (w - 1) / math.max(1, count - 1)); if opts.mode == "fill" then drawLine(xx, y + h - 1, xx, py, opts.colour or M.grey.bright) elseif opts.mode == "dots" or not previousX then drawRectangle(xx, py, xx, py, opts.colour or M.grey.bright) else drawLine(previousX, previousY, xx, py, opts.colour or M.grey.bright) end; previousX, previousY = xx, py end return M end
function M.curve(x, y, w, h, fn, opts) opts = opts or {}; local px, py; for i = 0, w - 1 do local value = num.clamp(fn(i / math.max(1, w - 1)), 0, 1); local yy = y + h - 1 - math.floor(value * (h - 1) + 0.5); if px then drawLine(px, py, x + i, yy, opts.colour or M.grey.bright) end px, py = x + i, yy end return M end
function M.envelope(x, y, w, h, envelope, opts) local a = envelope.times and envelope.times.attack or envelope.a or 0.1; local d = envelope.times and envelope.times.decay or envelope.d or 0.1; local s = envelope.sustain or envelope.s or 0.7; local r = envelope.times and envelope.times.release or envelope.r or 0.1; local total = math.max(1e-9, a + d + r); local ax, dx = x + math.floor(w * a / total), x + math.floor(w * (a + d) / total); drawLine(x, y + h - 1, ax, y, (opts and opts.colour) or M.grey.bright); drawLine(ax, y, dx, y + math.floor((1 - s) * (h - 1)), (opts and opts.colour) or M.grey.bright); drawLine(dx, y + math.floor((1 - s) * (h - 1)), x + w - 1, y + h - 1, (opts and opts.colour) or M.grey.bright); return M end
function M.steps(x, y, w, h, pattern, current, opts) opts = opts or {}; local count = opts.count or (pattern and (pattern.steps or pattern.length or #pattern)) or 16; local gap = opts.gap or 1; local sw = math.max(1, math.floor((w - gap * (count - 1)) / count)); for i = 1, count do local active = pattern and (pattern.at and pattern:at(i) or pattern.get and pattern:get(i) ~= 0 or pattern[i]); local colour = i == current and (opts.current or M.grey.full) or active and (opts.colour or M.grey.bright) or (opts.off or M.grey.faint); if opts.values and opts.values.get then colour = math.floor(num.clamp(opts.values:get(i), 0, 1) * 13 + 2) end; local xx = x + (i - 1) * (sw + gap); drawRectangle(xx, y, math.min(x + w - 1, xx + sw - 1), y + h - 1, colour) end return M end
function M.keyboard(x, y, w, h, mask, opts) opts = opts or {}; local width = w / 12; for pc = 0, 11 do local xx1, xx2 = math.floor(x + pc * width), math.floor(x + (pc + 1) * width - 1); local active = mask & (1 << pc) ~= 0; local colour = pc == opts.playing and (opts.playingColour or M.grey.full) or pc == opts.root and (opts.rootColour or M.grey.bright) or active and (opts.colour or M.grey.mid) or M.grey.faint; drawRectangle(xx1, y, xx2, y + h - 1, colour) end return M end
function M.piano(x, y, w, h, lowNote, highNote, notes, opts) opts = opts or {}; local count = math.max(1, highNote - lowNote + 1); for note = lowNote, highNote do local i = note - lowNote; local xx1, xx2 = math.floor(x + i * w / count), math.floor(x + (i + 1) * w / count - 1); local active = false; for j = 1, #notes do if notes[j] == note then active = true; break end end; drawRectangle(xx1, y, xx2, y + h - 1, active and (opts.colour or M.grey.full) or (((note % 12 == 1 or note % 12 == 3 or note % 12 == 6 or note % 12 == 8 or note % 12 == 10) and M.grey.dim) or M.grey.faint)) end return M end
function M.list(x, y, w, h, items, selected, scroll, opts) opts = opts or {}; local line = opts.lineHeight or 9; local first = math.max(1, math.floor(scroll or 1)); local rows = math.floor(h / line); for row = 0, rows - 1 do local index = first + row; if not items[index] then break end; if index == selected then drawRectangle(x, y + row * line, x + w - 1, y + row * line + line - 1, opts.selectedBg or M.grey.dim) end; drawText(x + 2, y + row * line + 7, tostring(items[index]), index == selected and (opts.selected or M.grey.full) or (opts.colour or M.grey.mid)) end return M end
function M.tabs(x, y, w, names, selected) local each = w / #names; for i = 1, #names do local cx = math.floor(x + (i - 0.5) * each); drawTinyText(cx, y, tostring(names[i]), i == selected and M.grey.full or M.grey.dim, "centre") end return M end
function M.formatter(format) local previous, result; return function(value) if value ~= previous then previous, result = value, string.format(format, value) end return result end end

return M
